/* tslint:disable */
/* eslint-disable */
/**
 * Chemically Peculiar Stars Database OpenAPI definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExternalDetails } from './ExternalDetails';
import {
    ExternalDetailsFromJSON,
    ExternalDetailsFromJSONTyped,
    ExternalDetailsToJSON,
} from './ExternalDetails';

/**
 * 
 * @export
 * @interface ExtendedStar
 */
export interface ExtendedStar {
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExtendedStar
     */
    consideredCategoryAffiliationProbabilityFlag?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedStar
     */
    renson?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedStar
     */
    binarySystemComponent?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    icrsRightAscension?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    icrsRightAscensionError?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    icrsDeclination?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    icrsDeclinationError?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    galacticLongitude?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedStar
     */
    galacticLatitude?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtendedStar
     */
    alpha?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedStar
     */
    delta?: string;
    /**
     * 
     * @type {ExternalDetails}
     * @memberof ExtendedStar
     */
    externalDetails?: ExternalDetails;
}

/**
 * Check if a given object implements the ExtendedStar interface.
 */
export function instanceOfExtendedStar(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ExtendedStarFromJSON(json: any): ExtendedStar {
    return ExtendedStarFromJSONTyped(json, false);
}

export function ExtendedStarFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedStar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'consideredCategoryAffiliationProbabilityFlag': !exists(json, 'consideredCategoryAffiliationProbabilityFlag') ? undefined : json['consideredCategoryAffiliationProbabilityFlag'],
        'renson': !exists(json, 'renson') ? undefined : json['renson'],
        'binarySystemComponent': !exists(json, 'binarySystemComponent') ? undefined : json['binarySystemComponent'],
        'icrsRightAscension': !exists(json, 'icrsRightAscension') ? undefined : json['icrsRightAscension'],
        'icrsRightAscensionError': !exists(json, 'icrsRightAscensionError') ? undefined : json['icrsRightAscensionError'],
        'icrsDeclination': !exists(json, 'icrsDeclination') ? undefined : json['icrsDeclination'],
        'icrsDeclinationError': !exists(json, 'icrsDeclinationError') ? undefined : json['icrsDeclinationError'],
        'galacticLongitude': !exists(json, 'galacticLongitude') ? undefined : json['galacticLongitude'],
        'galacticLatitude': !exists(json, 'galacticLatitude') ? undefined : json['galacticLatitude'],
        'alpha': !exists(json, 'alpha') ? undefined : json['alpha'],
        'delta': !exists(json, 'delta') ? undefined : json['delta'],
        'externalDetails': !exists(json, 'externalDetails') ? undefined : ExternalDetailsFromJSON(json['externalDetails']),
    };
}

export function ExtendedStarToJSON(value?: ExtendedStar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'consideredCategoryAffiliationProbabilityFlag': value.consideredCategoryAffiliationProbabilityFlag,
        'renson': value.renson,
        'binarySystemComponent': value.binarySystemComponent,
        'icrsRightAscension': value.icrsRightAscension,
        'icrsRightAscensionError': value.icrsRightAscensionError,
        'icrsDeclination': value.icrsDeclination,
        'icrsDeclinationError': value.icrsDeclinationError,
        'galacticLongitude': value.galacticLongitude,
        'galacticLatitude': value.galacticLatitude,
        'alpha': value.alpha,
        'delta': value.delta,
        'externalDetails': ExternalDetailsToJSON(value.externalDetails),
    };
}

