/* tslint:disable */
/* eslint-disable */
/**
 * Chemically Peculiar Stars Database OpenAPI definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSource } from './DataSource';
import {
    DataSourceFromJSON,
    DataSourceFromJSONTyped,
    DataSourceToJSON,
} from './DataSource';
import type { Star } from './Star';
import {
    StarFromJSON,
    StarFromJSONTyped,
    StarToJSON,
} from './Star';

/**
 * 
 * @export
 * @interface Magnitude
 */
export interface Magnitude {
    /**
     * 
     * @type {number}
     * @memberof Magnitude
     */
    id: number;
    /**
     * 
     * @type {Star}
     * @memberof Magnitude
     */
    star?: Star;
    /**
     * 
     * @type {DataSource}
     * @memberof Magnitude
     */
    datasource: DataSource;
    /**
     * 
     * @type {string}
     * @memberof Magnitude
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Magnitude
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof Magnitude
     */
    error?: number;
    /**
     * 
     * @type {string}
     * @memberof Magnitude
     */
    quality?: string;
    /**
     * 
     * @type {string}
     * @memberof Magnitude
     */
    uncertaintyFlag?: string;
}

/**
 * Check if a given object implements the Magnitude interface.
 */
export function instanceOfMagnitude(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "datasource" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function MagnitudeFromJSON(json: any): Magnitude {
    return MagnitudeFromJSONTyped(json, false);
}

export function MagnitudeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Magnitude {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'star': !exists(json, 'star') ? undefined : StarFromJSON(json['star']),
        'datasource': DataSourceFromJSON(json['datasource']),
        'name': json['name'],
        'value': json['value'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'quality': !exists(json, 'quality') ? undefined : json['quality'],
        'uncertaintyFlag': !exists(json, 'uncertaintyFlag') ? undefined : json['uncertaintyFlag'],
    };
}

export function MagnitudeToJSON(value?: Magnitude | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'star': StarToJSON(value.star),
        'datasource': DataSourceToJSON(value.datasource),
        'name': value.name,
        'value': value.value,
        'error': value.error,
        'quality': value.quality,
        'uncertaintyFlag': value.uncertaintyFlag,
    };
}

