/* tslint:disable */
/* eslint-disable */
/**
 * Chemically Peculiar Stars Database OpenAPI definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpectrumMeasurement
 */
export interface SpectrumMeasurement {
    /**
     * 
     * @type {number}
     * @memberof SpectrumMeasurement
     */
    wavelength?: number;
    /**
     * 
     * @type {number}
     * @memberof SpectrumMeasurement
     */
    flux?: number;
}

/**
 * Check if a given object implements the SpectrumMeasurement interface.
 */
export function instanceOfSpectrumMeasurement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SpectrumMeasurementFromJSON(json: any): SpectrumMeasurement {
    return SpectrumMeasurementFromJSONTyped(json, false);
}

export function SpectrumMeasurementFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpectrumMeasurement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wavelength': !exists(json, 'wavelength') ? undefined : json['wavelength'],
        'flux': !exists(json, 'flux') ? undefined : json['flux'],
    };
}

export function SpectrumMeasurementToJSON(value?: SpectrumMeasurement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wavelength': value.wavelength,
        'flux': value.flux,
    };
}

