/* tslint:disable */
/* eslint-disable */
/**
 * Chemically Peculiar Stars Database OpenAPI definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VizierTable
 */
export interface VizierTable {
    /**
     * 
     * @type {string}
     * @memberof VizierTable
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VizierTable
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof VizierTable
     */
    fields?: Array<string>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof VizierTable
     */
    data?: Array<Array<string>>;
}

/**
 * Check if a given object implements the VizierTable interface.
 */
export function instanceOfVizierTable(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VizierTableFromJSON(json: any): VizierTable {
    return VizierTableFromJSONTyped(json, false);
}

export function VizierTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): VizierTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function VizierTableToJSON(value?: VizierTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'fields': value.fields,
        'data': value.data,
    };
}

