/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSource } from './DataSource';
import {
    DataSourceFromJSON,
    DataSourceFromJSONTyped,
    DataSourceToJSON,
} from './DataSource';

/**
 * 
 * @export
 * @interface Motion
 */
export interface Motion {
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    id?: number;
    /**
     * 
     * @type {DataSource}
     * @memberof Motion
     */
    datasource?: DataSource;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    properMotionRa?: number;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    properMotionRaError?: number;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    properMotionDec?: number;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    properMotionDecError?: number;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    parallax?: number;
    /**
     * 
     * @type {number}
     * @memberof Motion
     */
    parallaxError?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Motion
     */
    defined?: boolean;
}

/**
 * Check if a given object implements the Motion interface.
 */
export function instanceOfMotion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MotionFromJSON(json: any): Motion {
    return MotionFromJSONTyped(json, false);
}

export function MotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Motion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'datasource': !exists(json, 'datasource') ? undefined : DataSourceFromJSON(json['datasource']),
        'properMotionRa': !exists(json, 'properMotionRa') ? undefined : json['properMotionRa'],
        'properMotionRaError': !exists(json, 'properMotionRaError') ? undefined : json['properMotionRaError'],
        'properMotionDec': !exists(json, 'properMotionDec') ? undefined : json['properMotionDec'],
        'properMotionDecError': !exists(json, 'properMotionDecError') ? undefined : json['properMotionDecError'],
        'parallax': !exists(json, 'parallax') ? undefined : json['parallax'],
        'parallaxError': !exists(json, 'parallaxError') ? undefined : json['parallaxError'],
        'defined': !exists(json, 'defined') ? undefined : json['defined'],
    };
}

export function MotionToJSON(value?: Motion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'datasource': DataSourceToJSON(value.datasource),
        'properMotionRa': value.properMotionRa,
        'properMotionRaError': value.properMotionRaError,
        'properMotionDec': value.properMotionDec,
        'properMotionDecError': value.properMotionDecError,
        'parallax': value.parallax,
        'parallaxError': value.parallaxError,
        'defined': value.defined,
    };
}

