/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttributeDefinition } from './AttributeDefinition';
import {
    AttributeDefinitionFromJSON,
    AttributeDefinitionFromJSONTyped,
    AttributeDefinitionToJSON,
} from './AttributeDefinition';
import type { DataSource } from './DataSource';
import {
    DataSourceFromJSON,
    DataSourceFromJSONTyped,
    DataSourceToJSON,
} from './DataSource';

/**
 * 
 * @export
 * @interface StarDatasourceAttribute
 */
export interface StarDatasourceAttribute {
    /**
     * 
     * @type {number}
     * @memberof StarDatasourceAttribute
     */
    id?: number;
    /**
     * 
     * @type {AttributeDefinition}
     * @memberof StarDatasourceAttribute
     */
    attributeDefinition?: AttributeDefinition;
    /**
     * 
     * @type {DataSource}
     * @memberof StarDatasourceAttribute
     */
    datasource?: DataSource;
    /**
     * 
     * @type {string}
     * @memberof StarDatasourceAttribute
     */
    value?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StarDatasourceAttribute
     */
    defined?: boolean;
}

/**
 * Check if a given object implements the StarDatasourceAttribute interface.
 */
export function instanceOfStarDatasourceAttribute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StarDatasourceAttributeFromJSON(json: any): StarDatasourceAttribute {
    return StarDatasourceAttributeFromJSONTyped(json, false);
}

export function StarDatasourceAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarDatasourceAttribute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributeDefinition': !exists(json, 'attributeDefinition') ? undefined : AttributeDefinitionFromJSON(json['attributeDefinition']),
        'datasource': !exists(json, 'datasource') ? undefined : DataSourceFromJSON(json['datasource']),
        'value': !exists(json, 'value') ? undefined : json['value'],
        'defined': !exists(json, 'defined') ? undefined : json['defined'],
    };
}

export function StarDatasourceAttributeToJSON(value?: StarDatasourceAttribute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributeDefinition': AttributeDefinitionToJSON(value.attributeDefinition),
        'datasource': DataSourceToJSON(value.datasource),
        'value': value.value,
        'defined': value.defined,
    };
}

