name: "Release"
on:
  push:
    tags:
      - '[1-9]*'
permissions:
  contents: write

jobs:
  release:
    name: "Build and package app"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build app"
        run: npm run build

      - name: "Package app"
        run: |
          tar -zcvf build.tar.gz -C build .

      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: cpstars-frontend-build
          path: build.tar.gz

      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: "Upload artifact to release"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build.tar.gz
          asset_name: cpstars-frontend-build.tgz
          asset_content_type: application/x-gzip
