name: "Release"
on:
  push:
    tags:
      - '[1-9]*'
permissions:
  contents: write

jobs:
  release:
    name: "Build and package app"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build app"
        run: npm run build

      - name: "Package app"
        uses: actions/upload-artifact@v2
        with:
          name: cpstars-frontend
          path: build/
