name: "Release"
on:
  push:
    tags:
      - '[1-9]*'
jobs:
  build:
    name: "Build and package app"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build app"
        run: npm run build

      - name: "Package app"
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/

  release:
    name: "Create release"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: "Install dependencies"
        run: npm ci

      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: "Upload assets"
        id: upload_assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: app.zip
          asset_content_type: application/zip
